### ISSUE TITLE
必须使用CocoaPods集成CocoaAsyncSocket才可以吗?

### ISSUE THREAD

**Issue by YangYiBo23** [TuyaInc/tuyasmart_ios_activator_sdk#1]
能不能手动集成CocoaAsyncSocket, 如果可以怎么集成?

**Comment by xuchengcheng** [comment]
可以支持手动继承CocoaAsyncSocket，具体参考 https://github.com/robbiehanson/CocoaAsyncSocket

Manual
You can also include it into your project by adding the source files directly, but you should probably be using a dependency manager to keep up to date.
